# Special tools.
LD					= $(CXX)
LDFLAGS				= -L$(BUILD_DIR) -lSDL2

# Rules.
.PHONY: all
all: 
	$(CXX) $(CXXFLAGS) -o $(BUILD_DIR)/minimal 1_minimal.cpp
	# $(CXX) $(CXXFLAGS) -o $(BUILD_DIR)/scrible 2_scrible.cpp
	# $(CXX) $(CXXFLAGS) -o $(BUILD_DIR)/calculator 3_calculator.cpp
